/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package proyectofinal.Vistas;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import proyectofinal.AccesoaDatos.AlojamientoData;
import proyectofinal.AccesoaDatos.CiudadData;
import proyectofinal.AccesoaDatos.PaqueteData;
import proyectofinal.Entidades.Ciudad;
import proyectofinal.Entidades.Paquete;

/**
 *
 * @author orell
 */
public class Consultas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Consultas
     */
    private DefaultTableModel modelo = new DefaultTableModel() {
        // Hacer que las columnas 1 hasta la 7 no sean editables
        @Override
        public boolean isCellEditable(int row, int column) {

            if (column == 7) { //Columna 1 hasta 7
                return true;
            } else {
                return false;
            }

        }
    };

    public Consultas() {
        initComponents();
        cargarComboPaises();
        cargarComboProvincias();
        armarCabecera();

        jcomboProvincia.setEnabled(false);
        jcomboMes.setEnabled(false);
        jbBuscar.setEnabled(false);
    }

    //************Variables Globales*******************
    CiudadData cData = new CiudadData();
    AlojamientoData ad = new AlojamientoData();

    ///***************************************************
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        menuConsultas1 = new proyectofinal.Vistas.componentes.MenuConsultas();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabla = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcomboPais = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jcomboProvincia = new javax.swing.JComboBox<>();
        jspCantidad = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jcomboMes = new javax.swing.JComboBox<>();
        jbBuscar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(700, 600));

        jPanel2.setMinimumSize(new java.awt.Dimension(500, 490));

        jTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTabla);

        jPanel3.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Selecione Pais Destino:");

        jcomboPais.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcomboPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jcomboPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboPaisActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Selecione Provincia:");

        jcomboProvincia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcomboProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboProvinciaActionPerformed(evt);
            }
        });

        jspCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Cantidad de Personas:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Selecione Mes:");

        jcomboMes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcomboMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jcomboMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboMesActionPerformed(evt);
            }
        });

        jbBuscar.setBackground(new java.awt.Color(255, 180, 4));
        jbBuscar.setForeground(new java.awt.Color(0, 0, 0));
        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jcomboMes, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jspCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbBuscar)))
                    .addComponent(jcomboProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcomboPais, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcomboPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcomboProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcomboMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jspCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, 0))
        );

        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Consultas de Paquetes");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal/Vistas/iconos/icons8-queries-66.png"))); // NOI18N

        javax.swing.GroupLayout menuConsultas1Layout = new javax.swing.GroupLayout(menuConsultas1);
        menuConsultas1.setLayout(menuConsultas1Layout);
        menuConsultas1Layout.setHorizontalGroup(
            menuConsultas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuConsultas1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(menuConsultas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuConsultas1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119))
                    .addGroup(menuConsultas1Layout.createSequentialGroup()
                        .addGroup(menuConsultas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(menuConsultas1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(114, 114, 114))))
        );
        menuConsultas1Layout.setVerticalGroup(
            menuConsultas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuConsultas1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuConsultas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(menuConsultas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(menuConsultas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcomboPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboPaisActionPerformed
        jcomboProvincia.setEnabled(true);

        cargarComboProvincias();


    }//GEN-LAST:event_jcomboPaisActionPerformed

    private void jcomboProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboProvinciaActionPerformed
        // TODO add your handling code here:
        jcomboMes.setEnabled(true);

    }//GEN-LAST:event_jcomboProvinciaActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:
        String pais = jcomboPais.getSelectedItem().toString();
        String provincia = jcomboProvincia.getSelectedItem().toString();
        String mes = jcomboMes.getSelectedItem().toString();
        int cantPersonas = (int) jspCantidad.getValue();

        int cantidadPersonas = (int) jspCantidad.getValue();
        ////////////////////////////////////////////////////////////////////////

        Ciudad ciu = new Ciudad();
        CiudadData ciuDat = new CiudadData();
        PaqueteData paquetedata = new PaqueteData();
        List<Paquete> paquete = new ArrayList();
        boolean flag = false;

        //********* Obteniendo ID Ciudades Destino por Provincias
        List<Ciudad> cd = ciuDat.listarCiudadPorProvinciaypais(pais, provincia);
        borrarFilas();
        for (Ciudad ciudad : cd) {

            int idCiudadDestTabla = ciudad.getIdCiudad();
            paquete = paquetedata.listarPaquetePorCiudad(idCiudadDestTabla);

            if (!paquete.isEmpty()) {
                    for (Paquete paq : paquete) {

                        String fechaIngreso = paq.getAlojamiento().getFechaing().getMonth().toString();
                        

                        String fe = traducir(fechaIngreso);
                        
                        if (mes.equalsIgnoreCase(fe)) {
                            flag = true;
                            String temporada = ad.CalcularTemporada(paq.getAlojamiento().getFechaing());
                            
                            int diasDeVacaciones = ad.CalcularDiasVacaciones(paq.getAlojamiento().getFechaing(), paq.getAlojamiento().getFechaOn());
                            double costoTotal = ((paq.getPasaje().getImporte() + (paq.getAlojamiento().getImporteDiario()* diasDeVacaciones)) * cantPersonas);
                            if (temporada.equalsIgnoreCase("alta")){
                                costoTotal *= 1.3;
                            }else if (temporada.equalsIgnoreCase("media")){
                                costoTotal *= 1.15;
                            }

                            modelo.addRow(new Object[]{
                                paq.getDestino().getNombre(),
                                paq.getAlojamiento().getFechaing(),
                                paq.getAlojamiento().getFechaOn(),
                                paq.getPasaje().getTipoTransporte(),
                                paq.getAlojamiento().getTipoAlojam(),
                                paq.getAlojamiento().getServicio(),
                                costoTotal
                            });
                        } else {
                           // JOptionPane.showMessageDialog(this, "No hay paquete para esa fecha");
                            flag = true;

                    }
                } 
            }

        }
        flag = false;
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jcomboMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboMesActionPerformed
        // TODO add your handling code here:
        jbBuscar.setEnabled(true);


    }//GEN-LAST:event_jcomboMesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabla;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JComboBox<String> jcomboMes;
    private javax.swing.JComboBox<String> jcomboPais;
    private javax.swing.JComboBox<Ciudad> jcomboProvincia;
    private javax.swing.JSpinner jspCantidad;
    private proyectofinal.Vistas.componentes.MenuConsultas menuConsultas1;
    // End of variables declaration//GEN-END:variables

    private void cargarComboPaises() {

        List<String> pais = cData.listarPaises();

        for (String pai : pais) {

            jcomboPais.addItem(pai);

        }

    }

    private void cargarComboProvincias() {
        String pai = (String) jcomboPais.getSelectedItem();

        List<Ciudad> ciudad = cData.listarProvinciasPorPaisCombo(pai);
        jcomboProvincia.removeAllItems();

        for (Ciudad ciudad1 : ciudad) {
            jcomboProvincia.addItem(ciudad1);
        }
    }

    private void armarCabecera() {
        modelo.addColumn("Ciudad");
        modelo.addColumn("Fecha Inicio");
        modelo.addColumn("Fecha Fin");
        modelo.addColumn("Transporte");
        modelo.addColumn("Alojamiento");
        modelo.addColumn("Servicios");
        modelo.addColumn("Precio Total");
        jTabla.setModel(modelo);
    }

    public String traducir(String fecha) {
        if (fecha.equalsIgnoreCase("october")) {
            fecha = "Octubre";

        } else if (fecha.equalsIgnoreCase("january")) {
            fecha = "Enero";
        } else if (fecha.equalsIgnoreCase("november")) {
            fecha = "Noviembre";
        } else if (fecha.equalsIgnoreCase("february")) {
            fecha = "Febrero";
        } else if (fecha.equalsIgnoreCase("march")) {
            fecha = "Marzo";
        } else if (fecha.equalsIgnoreCase("april")) {
            fecha = "Abril";
        } else if (fecha.equalsIgnoreCase("May")) {
            fecha = "Mayo";
        } else if (fecha.equalsIgnoreCase("june")) {
            fecha = "Junio";
        } else if (fecha.equalsIgnoreCase("july")) {
            fecha = "Julio";
        } else if (fecha.equalsIgnoreCase("august")) {
            fecha = "Agosto";
        } else if (fecha.equalsIgnoreCase("september")) {
            fecha = "Septiembre";
        } else if (fecha.equalsIgnoreCase("december")) {
            fecha = "Diciembre";
        }
        return fecha;
    }
    
     private void borrarFilas() {

        int filas = jTabla.getRowCount() - 1;

        for (int i = filas; i >= 0; i--) {

            modelo.removeRow(i);
        }
    }

}
